name: ci

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - esp32-s3-devkit
          - odroid-go
          - mrgc-g32

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build firmware
        run: |
          python3 rg_tool.py build ${{ matrix.target }}

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: retro-go-${{ matrix.target }}
          path: |
            build/*.bin
            build/*.fw
