name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v4.4
    strategy:
      matrix:
        target: [esp32-s3-devkit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          . $IDF_PATH/export.sh
          python3 rg_tool.py build ${{ matrix.target }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: retro-go_${{ matrix.target }}
          path: build/*.fw
